name       : mailcommon
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/mailcommon-21.04.1.tar.xz : 13dc5b7ef81f74463f63833876b717ed6c8a66d37a44f0cbeaa9b090362d7e71
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(phonon4qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - akonadi-mime-devel
        - libkdepim-devel
        - libkleo-devel
        - messagelib-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
