name       : mailcommon
version    : 18.08.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/mailcommon-18.08.3.tar.xz : 17ab7cad37a0bac8ae4baa075241571571a35b743b52c640717b9cf54a9382e8
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Designer)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
