name       : mailcommon
version    : 20.12.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/mailcommon-20.12.0.tar.xz : d5601ae3b93f37216c726b8b0173b7af2023a29e9116c3c3fcf574cd944b76ce
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(libsasl2)
    - pkgconfig(phonon4qt5)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - grantleetheme-devel
    - karchive-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
