name       : mailcommon
version    : 22.08.3
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/mailcommon-22.08.3.tar.xz : 88c54e22a9fb83e2ce17e52996ac54bcc21c7eb976eb636afa36f09bf28f6ffe
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(phonon4qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - akonadi-mime-devel
        - libkdepim-devel
        - libkleo-devel
        - messagelib-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
