name       : mailcommon
version    : 21.04.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/mailcommon-21.04.0.tar.xz : fd8137c4991f578dae0fdaf29e44330654b4fdff9adf9ce5fbd44e9bdd844cd2
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(phonon4qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - akonadi-mime-devel
        - libkdepim-devel
        - libkleo-devel
        - messagelib-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
