name       : mailcommon
version    : 18.04.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/mailcommon-18.04.1.tar.xz : 93e1ba7e5fd1ca1dce2d7a58c5ab52a4f396b258d881873f0c63e050b9260c68
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.library
optimize   : lto
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Designer)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
