name       : mailcommon
version    : 23.04.2
release    : 68
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/mailcommon-23.04.2.tar.xz : d02582735ebaea6d669e4b7393247b073299366d03681a87aa1c7d42d6e40857
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(phonon4qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - ktextaddons-devel
    - kmailtransport-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - akonadi-mime-devel
        - libkdepim-devel
        - libkleo-devel
        - messagelib-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
