name       : mailcommon
version    : 21.12.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/mailcommon-21.12.3.tar.xz : 4e8dcb2ece18dfca8e219838d85d8e402cb353e6a2ca8fa9d79bbcb4e1fc28fe
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : MailCommon Library
description: |
    MailCommon Library.
builddeps  :
    - pkgconfig(phonon4qt5)
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kmailtransport-devel
    - libkdepim-devel
    - libkleo-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
    - syntax-highlighting-devel
rundeps    :
    - devel :
        - akonadi-mime-devel
        - libkdepim-devel
        - libkleo-devel
        - messagelib-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
